language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install:
  - ./gradlew clean build jacocoTestVerify generateSwaggerDocumentation
after_success:
  - bash <(curl -s https://codecov.io/bash)